language: android
android:
  components:
    - build-tools-23.0.1
    - android-23
    - sys-img-armeabi-v7a-android-23
    - sys-img-x86-android-23
before_install:
  - chmod +x gradlew
script:
  - ./gradlew build connectedCheck