language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository
before_install:
  - chmod +x gradlew
script:
  - ./gradlew build connectedCheck